version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: rpb_serial
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: rpb_serial
    image: postgres:latest
    networks:
      - rpb_serial
    ports:
      - 5430:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    user: apiuser
    depends_on:
      - db
    environment:
      STAGE: dev
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://rpb_serial:dev@db/rpb_serial
      SQLALCHEMY_TRACK_MODIFICATIONS: 0
    networks:
      - rpb_serial
    ports:
      - 5000:5000
    volumes:
      - ./api:/opt/api
    restart: always

  app:
    build: ./app
    user: appuser
    depends_on:
      - api
    networks:
      - rpb_serial
    ports:
      - 3000:3000
    stdin_open: true

networks:
  rpb_serial:
